### ISSUE TITLE
wrong pin order CON1 in schematic and silk screen

### ISSUE THREAD

**Issue by feuera** [OLIMEX/LoRa-868-915#1]
In schematic and datasheet con1 has 1-1 and 8-8 mapping. In kicad pcb files and real world the pin mapping for con1 is reversed.

**Comment by nonsintetic** [comment]
Can confirm.. just bought 5 `LoRa868-ANT` boards (the small one, not `MOD-LoRa868`) and the pinout for CON1 is *indeed reversed* in all the documentation except the KiCAD file. The documentation and everything here is for Rev_B, but the boards I received are all Rev_A, couldn't find anything for that, maybe they just didn't finish updating everything.

Guess I have to throw away the custom PCBs i had made. I'm normally a big Olimex fan, but they really dropped the ball on this one. This issue is from 2021, over a year ago, it's just 2 PDF files to fix.

I have the `MOD-LoRa868` too, for that one the pinout in the PDF is correct.

**Comment by DanKoloff** [comment]
Thanks for the notice, sorry for the delay in response I somehow missed it, please in future use olimex@support.com for such hardware or design related issues. 

Sorry for the experience. It appears the designers made a mistake and there is no consistency between schematic, labelling, and PCB. White print is wrong. I will suggest to the team to swap 1 and 8 labels near CON1 in next revision.

> The documentation and everything here is for Rev_B, but the boards I received are all Rev_A, couldn't find anything for that, maybe they just didn't finish updating everything.

This part is the same for revision A and revision B. It is wrong in both schematics.

**Comment by DanKoloff** [comment]
Edited the schematic and the document. Now should be easier to notice the routing and naming. Will close this issue, if you notice other discrepancy please either open a new issue or better contact us at support@olimex.com
